### ISSUE TITLE
HS300 not listed in Discover.discover()

### ISSUE THREAD

**Issue by kevank** [GadgetReactor/pyHS100#167] opened 2019-03-25 00:02 UTC
Using the following code:

```
from pyHS100 import Discover

for dev in Discover.discover().values():
        print(dev)
```

The output lists HS100s and HS105s but nothing from the HS300.

Running cli.py does list the HS300 during discovery.

**Comment by kevank** [comment] 2019-03-25 00:41
Found out if I wait long enough it crashes with the linked error and traceback:
https://paste.tinyw.in/index.php/view/6abe9af6

**Comment by jimboca** [comment] 2019-03-26 23:33
Yes, that issue is mentioned in #165, this should be closed.

**Comment by eode** [comment] 2019-04-07 16:47
Agree, this issue should be closed.

**Comment by kirichkov** [comment] 2019-04-08 14:07
Closing as duplicate of #165

**Closed as completed by kirichkov** 2019-04-08 14:07 UTC
