### ISSUE TITLE
Adding to the API

### ISSUE THREAD

**Issue by kdschlosser** [GadgetReactor/pyHS100#57] opened 2017-05-14 18:14 UTC
I just wanted to let ya know I am adding the following to the API. I will submit a PR when I am done.
system:
setting device id*
setting hardware id*
setting location*
setting time zone
setting time
rebooting*
testing uboot*
checking config*
resetting device to factory defaults*

firmware:
setting firmware download url*
getting firmware list
downloading firmware*
installing firmware*

wifi:
scanning access points*
connecting to access point*

cloud:
getting cloud information
setting cloud server url
connecting to cloud server
unregistering device from the cloud

meter:
getting meter voltage gain and current gain
setting meter voltage gain and current gain
meter calibration

schedule:
getting schedule
getting next scheduled action
editing a schedule item
deleting schedule item
delete schedule for a device
   
countdown - action to perform one time after a given period of time:
adding countdown
editing countdown
deleting countdown
deleting all countdowns

anti-theft - actions to perform when mode is set to away:
get anti-theft list
new anti-theft
edit anti-theft
delete anti-theft
delete all anti-theft

*DONE

I also wanted to inform you that I have made a GUI front end with events that can be assigned to do different things when various states change.

Software can be downloaded here: http:\\www.eventghost.org
And the plugin that goes into the software can be had here: http://www.eventghost.net/forum/viewtopic.php?f=2&t=9648&p=46019#p46019

just in case you wanted to check it out.

**Comment by francisconroy** [comment] 2018-06-17 02:30
How are you progressing with the wifi features? I actually need to use them. Has your PR been submitted yet?

**Comment by kirichkov** [comment] 2018-06-18 11:57
I believe the PR was closed a few weeks ago due to inactivity.

**Comment by kdschlosser** [comment] 2018-06-18 16:39
sorry i have not gotten to this. I had a lot of thing take place and some of my projects ended up having to be put on the back burner. I will finish it up i just do not know when.

**Comment by francisconroy** [comment] 2018-07-07 01:18
Thanks for the update. I've taken some of your changes into my fork to use for now. Thanks for the work

**Comment by kdschlosser** [comment] 2018-07-07 06:31
I have been working on this a bit over the past 2 weeks. I will have to change the code in order to work with your library. I have a project that uses python 2.7 and since this library only supports python 3+ i had to write a python 2 version of it.

I have all of the above features working. The only thing left to do is to port the changes or I can zip up the code and you can add what ever features you want. Up to you how you want to go about it.

**Comment by kirichkov** [comment] 2018-07-08 12:24
We'd much rather prefer a pull request so we can review what's changed, etc.

**Comment by kdschlosser** [comment] 2018-07-08 20:13
OK cool. no worries there.

I have added a couple of things like the setting of the date and time as well as changed the discovery process to handle the possibility of a user having 2 network cards and the binding order set so that the network that the TPLink devices are on is not the first one in the list. It enumerates all NIC's and will send out a broadcast on each network that the NIC is associated with. Each NIC the discovery is run in it's own thread. so if the timeout is set to 3 seconds it will still take only 3 seconds to finish up.

There is also an issue with the Kasa App not setting the devices up properly and it has something to do with the setting of the time. So if this problem is encountered during the discovery process it will correct the issue on the device and restart the discovery. If  the issue is not corrected the schedules, countdown timer and anti-theft will not work. The problem only occurs during the setup of the device when it is initially configured.

I also mapped out the different encryption options for setting of the access point. and you are able to set the device to a network that does not have any encryption enabled YAY! Not being able to do that was actually coded into the Kasa app and not the device it's self.

I have been working on getting the schedule, countdown, and anti-theft added.

The date and time I created a helper class for and set that helper class into the smartdevice class as an attribute named "device_time". and the class has properties for getting and setting all of the different elements in the time. Month, Year, Day, Hour, Minute, Second. It also has a get and set method that returns/accepts a datetime.datetime instance.

As far as the time goes if you can pass me the returned json data for this query

    "time", dict(get_time=None, get_timezone=None)

this will be helpful in me mapping out the time zones. this way I can create a tzinfo subclass  that i can attach to the datetime.datetime instance and also use the tzinfo if one is attached in setting the timezone. They have some kind of an index for the time zones that doesn't match to the utc offset

**Comment by rytilahti** [comment] 2020-03-16 14:21
We are closing this repository for new changes in favor of a new, asyncio-enabled continuation project: https://github.com/python-kasa/python-kasa

If the issue is still present in the new project, please feel free to open an issue there, thanks!

**Closed as completed by rytilahti** 2020-03-16 14:21 UTC
