### ISSUE TITLE
Request to add support for usage time of HS100

### ISSUE THREAD

**Issue by backcountrymountains** [GadgetReactor/pyHS100#113] opened 2018-03-05 23:58 UTC
Thanks for this nifty tool! 

Warning: I don't know python or programming.

I have a HS100 that doesn't have the emeter but does collect hours of usage for the current day/month/year. I use it to estimate energy consumption from a fixed, known-wattage load.

The data can be accessed by sending a request for the schedule for the month and year. Yes, it returns the runtime, not a schedule.

The packet captured request looks like:
`"{\"schedule\":{\"get_monthstat\":{"year\":2018},\"get_daystat\":{"month\"3,\"year\":2018}}}"`

It returns the runtime of the outlet in minutes.

I can use _query_helper directly to get the data but I was wondering if you could add the requests into the smartdevice.py thing like the emeter polling stuff that's already there.

Also, the _query_helper thing breaks when I give it a long command like from the above packet capture.

I can use 
`plug._query_helper("schedule","get_monthstat", {"year":2018})`
 to get the monthly data and
`plug._query_helper("schedule","get_daystat",{month":3,"year":2018})`
to get the daily data for the 3rd month,
but if I try to combine the two,
`plug._query_helper("schedule","get_monthstat", {"year":2018},"get_daystat",{month":3,"year":2018})`
it breaks the _query_helper because of too many positional arguments.

I don't know how to fix that. 

Thanks!

**Comment by rytilahti** [comment] 2018-03-06 18:29
You can do those requests separately by calling `get_emeter_daily(2018, 3)` and `get_emeter_monthly(2018)`.

The queries are currently limited to a single target, that could be changed though in the future. For now you could imitate this by calling `plug.protocol.query()` directly, and modify the request to include both parts: https://github.com/GadgetReactor/pyHS100/blob/master/pyHS100/smartdevice.py#L74 .

**Comment by backcountrymountains** [comment] 2018-03-10 19:29
Thanks for the response!

So, the plug is an HS100 which has no emeter, but does record how long it's on for each day.
As such, the `get_emeter_() stuff` just returns "None".

However, your advice about calling `plug.protocol.query()` was super helpful!

I can run:
```
host = plug.host
request={"schedule":{"get_monthstat":{"year":2018},"get_daystat":{"month": 3, "year": 2018}}}
plug.protocol.query(host,request)
```
and it barfs out all the info about runtime per day/month that I was looking for!

Yay!

Perhaps such queries can find it's way into the code for the people that just have the HS100 and not the super cool emeter, HS110?

Thanks for the help!

**Comment by rytilahti** [comment] 2018-03-10 20:29
Glad you got it working! I suppose there is no harm adding support for that, I think the best way would be simply to modify the existing `get_emeter_()` calls to allow them work even for non-emeter ones. It would also solve the problem with unit types for these methods (see #107), I think the nicest way would be returning a dict of `{'time': x, 'power': y}` per key (be it a month or a day). If you prepare a PR I can do a review :-)

**Comment by Dhiyaddein** [comment] 2019-04-26 08:03
Hi. Din Here,

I have similar question. How do I get the total running hours of the machine from a specific timeline? For example; I have machine running from 1/1/2019 until 29/1/2019. I need to extract the running hour data for the machine starting from 15/1/2019 till 29/1/2019.
Additionally, how can I pass the data into my database. Should I modify the program in the smartplug.py? Thank you in advance

**Comment by rytilahti** [comment] 2019-06-04 04:37
@backcountrymountains could you please add an example how the output looks like, so it'd be possible to add support for this?

@Dhiyaddein maybe it is possible to request the monthly stat and create a script to do that? How to pass that data to a database is not related to this library, but the API returns dict objects you can easily encode as json or some other format your databases uses. But this is offtopic for this issue.

**Comment by sfjes** [comment] 2020-03-16 00:23
It'd be great to have support for erasing the runtime stats as well. I was able to erase it using the schedule erase_runtime_stat as below.

```
host = plug.host
request='{"schedule":{"erase_runtime_stat":null}}'
plug.protocol.query(host,request)
```

**Comment by rytilahti** [comment] 2020-03-16 13:31
Feel free to create a PR on https://github.com/python-kasa/python-kasa :-)

**Comment by rytilahti** [comment] 2020-03-16 14:21
We are closing this repository for new changes in favor of a new, asyncio-enabled continuation project: https://github.com/python-kasa/python-kasa

If the issue is still present in the new project, please feel free to open an issue there, thanks!

**Closed as completed by rytilahti** 2020-03-16 14:21 UTC
Labels: enhancement, help wanted
