### ISSUE TITLE
New protocol

### ISSUE THREAD

**Issue by bcaro** [GadgetReactor/pyHS100#175] opened 2019-07-08 05:53 UTC
Model : HS110
Version : 2.0
firmware : 1.5.4 
to change state:
 {"context":{"source":"4xxxxxxb-6xx9-4xxc-axx3-exxxxxxxxxx4"},"system":{"set_relay_state":{"state":0}}}
to obtain consumption:
{"context":{"source":"4xxxxxxb-6xx9-4xxc-axx3-exxxxxxxxxx4"},"emeter":{"get_realtime":{}}}
response is:
{"emeter":{"get_realtime":{"current_ma":41124,"voltage_mv":237500,"power_mw":9341,"total_wh":1000,"err_code":0}}}

Each plug has a token : 4xxxxxxb-6xx9-4xxc-axx3-exxxxxxxxxx4 
and the emeter response is slightly different

**Comment by kirichkov** [comment] 2019-07-08 14:44
Is the token really like this, or did you obfuscate it with "x"?

**Comment by bcaro** [comment] 2019-07-08 14:52
I obfuscate it.
It is possible to recover this token with Packet Capture. You capture data between kasa app and the device and after you have to decrypt as before.

**Comment by kirichkov** [comment] 2019-07-08 18:05
This looks strangely like an UUID :-)

**Comment by rytilahti** [comment] 2019-07-08 19:28
Can you do `pyhs100 dump-discover` using the current git master and create a PR under `pyHS100/tests/fixtures/`? I hope that the context can be extracted from the discovery responses (similarly to how it's done for smart strips), but this will still require some changes on how the context is currently being handled inside `SmartDevice`.

**Comment by rytilahti** [comment] 2020-03-16 14:21
We are closing this repository for new changes in favor of a new, asyncio-enabled continuation project: https://github.com/python-kasa/python-kasa

If the issue is still present in the new project, please feel free to open an issue there, thanks!

**Closed as completed by rytilahti** 2020-03-16 14:21 UTC
Labels: enhancement, help wanted
