### ISSUE TITLE
Trying to get state with pyhs100 on LB100 fails.

### ISSUE THREAD

**Issue by slick8086** [GadgetReactor/pyHS100#51] opened 2017-04-22 05:44 UTC
Additionally I tried on/off but those didn't do anything and there was no response.

This is the error output:
```bash
$ pyhs100 --ip 172.16.1.132 state
== Bedroom Light - LB100(US) ==
Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 9, in <module>
    load_entry_point('pyHS100==0.2.4.2', 'console_scripts', 'pyhs100')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyHS100-0.2.4.2-py3.5.egg/pyHS100/cli.py", line 67, in state
    click.echo(click.style("Device state: %s" % plug.state,
  File "/usr/local/lib/python3.5/dist-packages/pyHS100-0.2.4.2-py3.5.egg/pyHS100/smartplug.py", line 55, in state
    relay_state = self.sys_info['relay_state']
KeyError: 'relay_state'
```

**Comment by kirichkov** [comment] 2017-04-24 07:34
From this dump it appears that the returned json from the light bulb is not in the expected format and is missing the bulb's state (on/off). Since none of us has a light bulb it's difficult to debug this without knowing what exactly it is returning. 

If you can provide us with the returned json from the bulb we can look into it.

**Comment by slick8086** [comment] 2017-04-24 13:16
Just quick this morning I have this, dunno if it will help.  I'll have to dig into it to get the output of that specific command but this is the output from pyhs100 discover:

```bash
$ pyhs100 discover
Discovering devices for 5 seconds
Found device: {'ip': '192.168.1.XXX',
 'port': 9999,
 'sys_info': {'emeter': {'err_code': -2001, 'err_msg': 'Module not support'},
              'system': {'get_sysinfo': {'active_mode': 'none',
                                         'alias': 'Bedroom Light',
                                         'ctrl_protocols': {'name': 'Linkie',
                                                            'version': '1.0'},
                                         'description': 'Smart Wi-Fi LED Bulb '
                                                        'with Dimmable Light',
                                         'dev_state': 'normal',
                                         'deviceId': '==REDACTED==',
                                         'disco_ver': '1.0',
                                         'err_code': 0,
                                         'heapsize': 416652,
                                         'hwId': '==REDACTED==',
                                         'hw_ver': '1.0',
                                         'is_color': 0,
                                         'is_dimmable': 1,
                                         'is_factory': False,
                                         'is_variable_color_temp': 0,
                                         'light_state': {'brightness': 100,
                                                         'color_temp': 2700,
                                                         'hue': 0,
                                                         'mode': 'normal',
                                                         'on_off': 1,
                                                         'saturation': 0},
                                         'mic_mac': '==REDACTED==',
                                         'mic_type': 'IOT.SMARTBULB',
                                         'model': 'LB100(US)',
                                         'oemId': '==REDACTED==',
                                         'preferred_state': [{'brightness': 100,
                                                              'color_temp': 2700,
                                                              'hue': 0,
                                                              'index': 0,
                                                              'saturation': 0},
                                                             {'brightness': 75,
                                                              'color_temp': 2700,
                                                              'hue': 0,
                                                              'index': 1,
                                                              'saturation': 0},
                                                             {'brightness': 25,
                                                              'color_temp': 2700,
                                                              'hue': 0,
                                                              'index': 2,
                                                              'saturation': 0},
                                                             {'brightness': 1,
                                                              'color_temp': 2700,
                                                              'hue': 0,
                                                              'index': 3,
                                                              'saturation': 0}],
                                         'rssi': -56,
                                         'sw_ver': '1.0.9 Build 160524 '
                                                   'Rel.100333'}}}}
````

**Comment by kirichkov** [comment] 2017-04-24 14:20
Yeah that helps, indeed. 

However, the CLI doesn't support the light bulbs, it only supports the plugs at this point. So if you want to interact with the bulbs you should try pull request https://github.com/GadgetReactor/pyHS100/pull/50 which adds (untested) support for interacting with the bulbs via the cli.py.

This is also a duplicate of #48 so if you have any feedback regarding the pull request above, please submit it there.

**Closed as completed by kirichkov** 2017-04-24 14:20 UTC
