### ISSUE TITLE
alias, state, and is_on not functional in SmartPlug for SmartStrip.plug[] devices

### ISSUE THREAD

**Issue by scootdj** [GadgetReactor/pyHS100#166] opened 2019-03-14 21:54 UTC
SmartDevice and SmartPlug return sys_info values for alias, relay_state, and is_on without checking for self.context and SmartDevice.plug specific values.

I'm attaching a patch file for changes that follow the existing pattern in other sections and checks for self.context and if true uses the child state info.
[pyHS100.patch.zip](https://github.com/GadgetReactor/pyHS100/files/2968612/pyHS100.patch.zip)

**Comment by rytilahti** [comment] 2019-04-09 04:20
Could you please create a PR? That will make it easier to review the code, thanks!

**Comment by rytilahti** [comment] 2020-03-16 14:21
We are closing this repository for new changes in favor of a new, asyncio-enabled continuation project: https://github.com/python-kasa/python-kasa

If the issue is still present in the new project, please feel free to open an issue there, thanks!

**Closed as completed by rytilahti** 2020-03-16 14:21 UTC
