### ISSUE TITLE
HS220 Set Brightness

### ISSUE THREAD

**Issue by scknowles** [GadgetReactor/pyHS100#193] opened 2020-02-11 16:35 UTC
When calling an HS220 to set_brightness it first turns on at previous level then dims the set brightness rather than initially turning on at the specified brightness.

I believe this is due to the order of operations here:

https://github.com/GadgetReactor/pyHS100/blob/59424d2738866a2bf88f8e256ece2baa06f0b024/pyHS100/smartplug.py#L110

**Comment by rytilahti** [comment] 2020-03-16 14:21
We are closing this repository for new changes in favor of a new, asyncio-enabled continuation project: https://github.com/python-kasa/python-kasa

If the issue is still present in the new project, please feel free to open an issue there, thanks!

**Closed as completed by rytilahti** 2020-03-16 14:21 UTC
