### ISSUE TITLE
Failing to work with a HS100

### ISSUE THREAD

**Issue by takigama** [GadgetReactor/pyHS100#39] opened 2017-03-08 14:56 UTC
Hi,

Im quite poor with python, so my abilities to debug it are quite limited, but getting an issue talking to a HS100 plug, and it appears the plug doesnt reply to some of the commands the protocol is sending:

```
$ python3 -m cli.py 10.10.20.121
DEBUG:pyHS100.protocol:> (31) {"system": {"get_sysinfo": {}}}
DEBUG:pyHS100.protocol:< (0) 
Traceback (most recent call last):
  File "/root/.homeassistant/deps/pyHS100/pyHS100.py", line 99, in _query_helper
    request={target: {cmd: arg}}
  File "/root/.homeassistant/deps/pyHS100/protocol.py", line 65, in query
    return json.loads(response)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/pyHS100/examples/cli.py", line 15, in <module>
    logging.info("Identify: %s", hs.identify())
  File "/root/.homeassistant/deps/pyHS100/pyHS100.py", line 317, in identify
    info = self.sys_info
  File "/root/.homeassistant/deps/pyHS100/pyHS100.py", line 119, in sys_info
    return self.get_sysinfo()
  File "/root/.homeassistant/deps/pyHS100/pyHS100.py", line 171, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/root/.homeassistant/deps/pyHS100/pyHS100.py", line 102, in _query_helper
    raise SmartPlugException(ex) from ex
pyHS100.pyHS100.SmartPlugException: Expecting value: line 1 column 1 (char 0)
```

The plug itself is up to date (or at least, kasa claims that it is) and im using the 0.2.3 pyHS100 version

Usinig the nodejs library, which hasnt been updated in a while, the plug does appear to respond correctly to the same command (including this only cause it may help?):
```
{ sw_ver: '1.0.10 Build 161012 Rel.165510',
  hw_ver: '2.0',
  type: 'IOT.SMARTPLUGSWITCH',
  model: 'HS100(AU)',
  mac: '50:C7:BF:39:87:C5',
  dev_name: 'Smart Wi-Fi Plug',
  alias: 'Plug02',
  relay_state: 1,
  on_time: 272,
  active_mode: 'none',
  feature: 'TIM',
  updating: 0,
  icon_hash: '',
  rssi: -44,
  led_off: 0,
  longitude_i: 1510659,
  latitude_i: -337919,
  hwId: 'D3CB232A2C936C37AE441A16BD2CBE64',
  fwId: '00000000000000000000000000000000',
  deviceId: '80062E7347A7D01037A56CED093D21D318236703',
  oemId: '2768475E8EC1F98BD216C2BF981B2DD1',
  err_code: 0 }
```

**Comment by mweinelt** [comment] 2017-03-14 16:15
You probably need the protocol communication enhancements from https://github.com/GadgetReactor/pyHS100/commit/2d6376b597eecdc15b881c34437bc057d8163145, this is unfortunately one commit ahead of 0.2.3.

**Comment by rytilahti** [comment] 2017-03-17 13:30
This is duplicate of #37.

**Closed as completed by rytilahti** 2017-03-17 13:30 UTC
