### ISSUE TITLE
Netdata module

### ISSUE THREAD

**Issue by Moltenkore** [GadgetReactor/pyHS100#152] opened 2019-01-14 20:11 UTC
Hello! Thanks for making this library and just to let you know, I wrote a Netdata module that uses pyHS100 to probe E-meter devices for real-time power data.

https://github.com/Moltenkore/netdata-pyHS100-module

![screenshot](https://raw.githubusercontent.com/Moltenkore/netdata-pyHS100-module/master/screenshot.png)

**Comment by rytilahti** [comment] 2019-01-14 20:30
Nice to hear that you have find it useful! Looking at your README, a simpler way to install this library is simply executing `pip install pyHS100` (so no need to git clone, install deps separately and so on :-).

edit: If you want, feel free to create a PR to add a link to your module (adding a new section "Users of this library" or similar). Having some links to real-world usage examples is always nice!

**Comment by rytilahti** [comment] 2020-03-16 14:21
We are closing this repository for new changes in favor of a new, asyncio-enabled continuation project: https://github.com/python-kasa/python-kasa

If the issue is still present in the new project, please feel free to open an issue there, thanks!

**Closed as completed by rytilahti** 2020-03-16 14:21 UTC
