### ISSUE TITLE
Fully implement the TP-Link Smart Home Protocol

### ISSUE THREAD

**Issue by mweinelt** [GadgetReactor/pyHS100#10] opened 2016-11-24 23:36 UTC
Existing commands are referenced here: https://github.com/softScheck/tplink-smartplug/blob/master/tplink-smarthome-commands.txt

We should try and implement the existing ones with a sane documentation of input values, which might be a bit difficult when it comes to things like setting the timezone.

**Comment by rytilahti** [comment] 2016-12-06 01:06
Some more API is implemented in #11. The case of timezone is unclear, but from looks of it they have a a hard-coded array of possible values + offset for those (as returned by get_timezone()), but set_timezone() itself is the setter for time() where index indicates the selected timezone. There seem to be no separate set_time() there.

**Comment by rytilahti** [comment] 2017-04-08 00:27
For light bulbs see https://github.com/softScheck/tplink-smartplug/pull/6 and https://github.com/konsumer/tplink-lightbulb .

**Comment by rytilahti** [comment] 2020-03-16 14:21
We are closing this repository for new changes in favor of a new, asyncio-enabled continuation project: https://github.com/python-kasa/python-kasa

If the issue is still present in the new project, please feel free to open an issue there, thanks!

**Closed as completed by rytilahti** 2020-03-16 14:21 UTC
Labels: enhancement, help wanted
