### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by vangorra** [GadgetReactor/pyHS100#183] opened 2019-11-09 04:00 UTC
There have been a lot of changes since the 0.3.5 release. Like cached state responses.
Is there any intention to release to pypi anytime soon?

**Comment by rytilahti** [comment] 2019-11-10 23:26
Yes, it's on my pipeline. I haven't yet managed to finalize cleaning up the powerstrip API, but it's almost done. I'll try to find some time during the upcoming week to do just that, after which I'll do a `0.40.dev0` tagging/prerelease to hopefully get some people to give it a try to iron potential problems before pushing a real release out.

**Comment by rytilahti** [comment] 2020-03-16 14:21
We are closing this repository for new changes in favor of a new, asyncio-enabled continuation project: https://github.com/python-kasa/python-kasa

If the issue is still present in the new project, please feel free to open an issue there, thanks!

**Closed as completed by rytilahti** 2020-03-16 14:21 UTC
